class Product {
  final int productID;
  final String productName;
  final int unitPrice;
  final double sellingPrice;
  final int quantity;
  final double weight;
  final String status;

  Product({
    required this.productID,
    required this.productName,
    required this.unitPrice,
    required this.sellingPrice,
    required this.quantity,
    required this.weight,
    required this.status,
  });
}

List<Product> products = [
  Product(
    productID: 1,
    productName: 'Product A',
    unitPrice: 20,
    sellingPrice: 30.5,
    quantity: 100,
    weight: 1.5,
    status: 'In Stock',
  ),
  Product(
    productID: 2,
    productName: 'Product B',
    unitPrice: 15,
    sellingPrice: 25.0,
    quantity: 50,
    weight: 2.0,
    status: 'Out of Stock',
  ),
  Product(
    productID: 3,
    productName: 'Product C',
    unitPrice: 30,
    sellingPrice: 45.75,
    quantity: 75,
    weight: 1.8,
    status: 'In Stock',
  ),
  Product(
    productID: 4,
    productName: 'Product D',
    unitPrice: 25,
    sellingPrice: 35.2,
    quantity: 120,
    weight: 2.5,
    status: 'In Stock',
  ),
  Product(
    productID: 5,
    productName: 'Product E',
    unitPrice: 18,
    sellingPrice: 28.9,
    quantity: 80,
    weight: 1.2,
    status: 'Out of Stock',
  ),
  Product(
    productID: 6,
    productName: 'Product F',
    unitPrice: 22,
    sellingPrice: 32.0,
    quantity: 60,
    weight: 2.2,
    status: 'In Stock',
  ),
  Product(
    productID: 7,
    productName: 'Product G',
    unitPrice: 28,
    sellingPrice: 40.6,
    quantity: 90,
    weight: 1.7,
    status: 'Out of Stock',
  ),
  Product(
    productID: 8,
    productName: 'Product H',
    unitPrice: 16,
    sellingPrice: 26.8,
    quantity: 110,
    weight: 1.4,
    status: 'In Stock',
  ),
  Product(
    productID: 9,
    productName: 'Product I',
    unitPrice: 24,
    sellingPrice: 38.2,
    quantity: 70,
    weight: 2.8,
    status: 'In Stock',
  ),
  Product(
    productID: 10,
    productName: 'Product J',
    unitPrice: 32,
    sellingPrice: 48.3,
    quantity: 40,
    weight: 2.3,
    status: 'Out of Stock',
  ),
  Product(
    productID: 11,
    productName: 'Product K',
    unitPrice: 25,
    sellingPrice: 37.5,
    quantity: 30,
    weight: 1.8,
    status: 'In Stock',
  ),
  Product(
    productID: 12,
    productName: 'Product L',
    unitPrice: 18,
    sellingPrice: 26.5,
    quantity: 50,
    weight: 1.5,
    status: 'In Stock',
  ),
  Product(
    productID: 13,
    productName: 'Product M',
    unitPrice: 42,
    sellingPrice: 56.8,
    quantity: 20,
    weight: 3.2,
    status: 'Out of Stock',
  ),
  Product(
    productID: 14,
    productName: 'Product N',
    unitPrice: 30,
    sellingPrice: 45.2,
    quantity: 35,
    weight: 2.5,
    status: 'In Stock',
  ),
  Product(
    productID: 15,
    productName: 'Product O',
    unitPrice: 22,
    sellingPrice: 34.7,
    quantity: 25,
    weight: 1.2,
    status: 'In Stock',
  ),
  Product(
    productID: 16,
    productName: 'Product P',
    unitPrice: 36,
    sellingPrice: 49.6,
    quantity: 15,
    weight: 2.0,
    status: 'Out of Stock',
  ),
];
